### ISSUE TITLE
Configuración en fichero

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-zoso_games#3]
En la versión actual de vuestro programa, la configuración está definida mediante directivas #define...
https://github.com/aigora/twE105_1920-zoso_games/blob/6ef61fbba3d25b3bdc977bc9e906721f3fe4aaa9/tablero_elementos.h#L3-L12

Os propongo que empleéis ficheros de configuración para almacenar esta información. De esta forma ganáis en flexibilidad, dado que para modificar la configuración del programa no es necesario cambiar el código y volver a compilar, sino únicamente modificar el fichero de configuración que corresponda.

**Comment by DiegoBastida** [comment]
No mejoramos este aspecto
